services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Emotib@t15.
      MYSQL_DATABASE: API_REST
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:   # Agrega esto para exponer el puerto
      - "3307:3306"

  api_res:
    build: .
    image: apirest:v1.0  # Especifica el nombre y la etiqueta de la imagen
    depends_on:
      - mariadb
    command: ["./wait-for-it.sh", "mariadb:3306", "--", "/usr/local/bin/app"]
    environment:
      DATABASE_URL: "root:Emotib@t15.@tcp(mariadb:3306)/API_REST"
    ports:
      - "3000:3000"  # Exponer el puerto 3000

volumes:
  db_data:



