apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-frontend
spec:
  replicas: 5  # 5 réplicas para escalar también el frontend
  selector:
    matchLabels:
      app: apache-frontend
  template:
    metadata:
      labels:
        app: apache-frontend
    spec:
      containers:
        - name: apache-frontend
          image: emotibotmessi/apache-frontend:v1.0  # Imagen de tu frontend
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-volume
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: frontend-volume
          hostPath:
            path: /usr/local/apache2/htdocs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: apache-frontend
spec:
  type: NodePort
  selector:
    app: apache-frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30081 
