apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest
spec:
  replicas: 5  # 5 réplicas para la escalabilidad
  selector:
    matchLabels:
      app: api-rest
  template:
    metadata:
      labels:
        app: api-rest
    spec:
      containers:
        - name: api-rest
          image: emotibotmessi/apirest:v1.0  # Imagen de tu API
          env:
            - name: DATABASE_URL
              value: "root:Emotib@t15.@tcp(mariadb-services:3306)/API_REST"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-rest
spec:
  type: NodePort
  selector:
    app: api-rest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
