apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Emotib@t15.
        - name: MYSQL_DATABASE
          value: API_REST
        volumeMounts:
        # Volumen para datos persistentes
        - name: db-data
          mountPath: /var/lib/mysql
        # Volumen para scripts de inicialización
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - "-h"
            - "127.0.0.1"
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      # Volumen para datos persistentes
      - name: db-data
        emptyDir: {}  # Volumen temporal; para producción, usa PersistentVolume
      # Volumen para scripts de inicialización
      - name: init-scripts
        hostPath:
          path: /docker-entrypoint-initdb.d
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32001
  selector:
    app: mariadb



